### ISSUE TITLE
Adding ProcessId property to Control class

### ISSUE THREAD

**Issue by thu2004** [yinkaisheng/Python-UIAutomation-for-Windows#1]
Hi !

I tried to add ProcessId property 
```python
class Control():
 @property
    def ProcessId(self):
        '''Return process id'''
        return ClientObject.dll.GetProcessId(self.Element)
```
and when I call the property I got this error message

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\python27\lib\ctypes\__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "C:\python27\lib\ctypes\__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'GetElementProcessId' not found
```

**Comment by yinkaisheng** [comment]
Fixed.
add 3 Control properties: ProcessId, HasKeyboardFocus and IsKeyboardFocusable
