### ISSUE TITLE
KeyError and TypeError occurred

### ISSUE THREAD

**Issue by haha198566** [yinkaisheng/Python-UIAutomation-for-Windows#108]
win10 64bit OS
I installed py3.7.6 64bit and depends on comtypes and typing, run CMD as administrator,when I run automation.py -h,some error occurred:
C:\python37\Scripts>automation.py -h
UIAutomation 2.0.3 (Python 3.7.6, 64 bit)
please wait for 3 seconds

2020-01-06 16:22:28.715 automation.py[75] main -> Starts, Current Cursor Position: (2168, 403)
Traceback (most recent call last):
  File "C:\python37\lib\ctypes\__init__.py", line 121, in WINFUNCTYPE
    return _win_functype_cache[(restype, argtypes, flags)]
KeyError: (<class 'ctypes.HRESULT'>, (<class 'ctypes.c_long'>, <class 'comtypes.automation.tagVARIANT'>, <class 'comtypes.LP_POINTER(IUIAutomationCondition)'>), 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python37\Scripts\automation.py", line 113, in <module>
    main()
  File "C:\python37\Scripts\automation.py", line 97, in main
    control = auto.GetFocusedControl()
  File "C:\python37\lib\site-packages\uiautomation\uiautomation.py", line 7465, in GetFocusedControl
    return Control.CreateControlFromElement(_AutomationClient.instance().IUIAutomation.GetFocusedElement())
  File "C:\python37\lib\site-packages\uiautomation\uiautomation.py", line 51, in instance
    cls._instance = cls()
  File "C:\python37\lib\site-packages\uiautomation\uiautomation.py", line 56, in __init__
    self.UIAutomationCore = comtypes.client.GetModule("UIAutomationCore.dll")
  File "C:\python37\lib\site-packages\comtypes\client\_generate.py", line 110, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\python37\lib\site-packages\comtypes\client\_generate.py", line 184, in _CreateWrapper
    mod = _my_import(fullname)
  File "C:\python37\lib\site-packages\comtypes\client\_generate.py", line 24, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "C:\python37\lib\site-packages\comtypes\gen\_944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0.py", line 1729, in <module>
    ( ['out', 'retval'], POINTER(POINTER(IUIAutomationElement)), 'element' )),
  File "C:\python37\lib\site-packages\comtypes\__init__.py", line 329, in __setattr__
    self._make_methods(value)
  File "C:\python37\lib\site-packages\comtypes\__init__.py", line 698, in _make_methods
    prototype = WINFUNCTYPE(restype, *argtypes)
  File "C:\python37\lib\ctypes\__init__.py", line 123, in WINFUNCTYPE
    class WinFunctionType(_CFuncPtr):
TypeError: item 2 in _argtypes_ passes a union by value, which is unsupported.
please help

**Comment by pangshu2007** [comment]
Me too.

**Comment by burque505** [comment]
Win7 Pro SP1,64-bit, identical error.

**Comment by yinkaisheng** [comment]
Do not use 3.7.6 and 3.8.1, install a earlier version.
https://github.com/enthought/comtypes/issues/202
