### ISSUE TITLE
uiautomation.py 代码逻辑bug

### ISSUE THREAD

**Issue by KevinChann** [yinkaisheng/Python-UIAutomation-for-Windows#113]
## 环境
- win10 1909
- python 3.6.3
- uiautomation 2.0.4

## 问题
使用非管理员权限的cmd运行命令 `automation -h` 报错，异常信息如下
```
UIAutomation 2.0.4 (Python 3.6.3, 64 bit)
PermissionError: can't write the log!Traceback (most recent call last):
  File "C:\Program Files\Python36\Scripts\automation.py", line 113, in <module>
    main()
  File "C:\Program Files\Python36\Scripts\automation.py", line 38, in main
    auto.Logger.Write('UIAutomation {} (Python {}.{}.{}, {} bit)\n'.format(auto.VERSION, sys.version_info.major, sys.version_info.minor, sys.version_info.micro, 64 if sys.maxsize > 0xFFFFFFFF else 32))
  File "c:\program files\python36\lib\site-packages\uiautomation\uiautomation.py", line 2788, in Write
    if fout:
UnboundLocalError: local variable 'fout' referenced before assignment
```

错误是 `\uiautomation.py", line 2788` ，错误代码：
```
        try:
            fout = open(fileName, 'a+', encoding='utf-8')
            fout.write(log)
        except Exception as ex:
            if sys.stdout:
                sys.stdout.write(ex.__class__.__name__ + ': can\'t write the log!')
        finally:
            if fout:
                fout.close()
```

## 错误原因
文件open时出 **PermissionError** 异常了，导致`fout`这个变量没创建，`finally`直接使用了 `if fout`，建议先声明变量 `fout  = None`

**Comment by yinkaisheng** [comment]
感谢，已修改。
