### ISSUE TITLE
win10系统下，无法获取控件，请求帮忙

### ISSUE THREAD

**Issue by Damon0635** [yinkaisheng/Python-UIAutomation-for-Windows#121]
D:\Programs\Python\Python37\Scripts>automation.py -r -d 1 -t 0
UIAutomation 2.0.5 (Python 3.7.6, 64 bit)
2020-06-19 10:52:22.523 automation.py[75] main -> Starts, Current Cursor Position: (306, 394)
Traceback (most recent call last):
  File "d:\programs\python\python37\lib\ctypes\__init__.py", line 121, in WINFUNCTYPE
    return _win_functype_cache[(restype, argtypes, flags)]
KeyError: (<class 'ctypes.HRESULT'>, (<class 'ctypes.c_long'>, <class 'comtypes.automation.tagVARIANT'>, <class 'comtypes.LP_POINTER(IUIAutomationCondition)'>), 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Programs\Python\Python37\Scripts\automation.py", line 113, in <module>
    main()
  File "D:\Programs\Python\Python37\Scripts\automation.py", line 78, in main
    control = auto.GetRootControl()
  File "d:\programs\python\python37\lib\site-packages\uiautomation\uiautomation.py", line 7465, in GetRootControl
    return Control.CreateControlFromElement(_AutomationClient.instance().IUIAutomation.GetRootElement())
  File "d:\programs\python\python37\lib\site-packages\uiautomation\uiautomation.py", line 51, in instance
    cls._instance = cls()
  File "d:\programs\python\python37\lib\site-packages\uiautomation\uiautomation.py", line 56, in __init__
    self.UIAutomationCore = comtypes.client.GetModule("UIAutomationCore.dll")
  File "d:\programs\python\python37\lib\site-packages\comtypes\client\_generate.py", line 110, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "d:\programs\python\python37\lib\site-packages\comtypes\client\_generate.py", line 184, in _CreateWrapper
    mod = _my_import(fullname)
  File "d:\programs\python\python37\lib\site-packages\comtypes\client\_generate.py", line 24, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "d:\programs\python\python37\lib\site-packages\comtypes\gen\_944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0.py", line 1870, in <module>
    ( ['out', 'retval'], POINTER(POINTER(IUIAutomationElement)), 'element' )),
  File "d:\programs\python\python37\lib\site-packages\comtypes\__init__.py", line 329, in __setattr__
    self._make_methods(value)
  File "d:\programs\python\python37\lib\site-packages\comtypes\__init__.py", line 698, in _make_methods
    prototype = WINFUNCTYPE(restype, *argtypes)
  File "d:\programs\python\python37\lib\ctypes\__init__.py", line 123, in WINFUNCTYPE
    class WinFunctionType(_CFuncPtr):
TypeError: item 2 in _argtypes_ passes a union by value, which is unsupported.

**Comment by yinkaisheng** [comment]
![image](https://user-images.githubusercontent.com/5846696/85723436-d39a5000-b725-11ea-81fe-b646e16d7d5f.png)
