### ISSUE TITLE
GetConsoleWindow老是返回nonetype，导致无法active

### ISSUE THREAD

**Issue by dulangnwpu** [yinkaisheng/Python-UIAutomation-for-Windows#124]
GetConsoleWindow老是返回nonetype，导致无法active

**Comment by dulangnwpu** [comment]
执行demo automation_devicemanager：
提示
Traceback (most recent call last):
  File "D:/春哥 项目/Python-UIAutomation-for-Windows-master/demos/automation_devicemanager.py", line 95, in <module>
    main()
  File "D:/春哥 项目/Python-UIAutomation-for-Windows-master/demos/automation_devicemanager.py", line 16, in main
    cmdTransformPattern = cmdWindow.GetTransformPattern()
AttributeError: 'NoneType' object has no attribute 'GetTransformPattern'

Process finished with exit code 1

**Comment by yinkaisheng** [comment]
已修改，用最新代码试下
