### ISSUE TITLE
win10下关于BoundingRectangle报错的问题

### ISSUE THREAD

**Issue by jackywang75** [yinkaisheng/Python-UIAutomation-for-Windows#125]
大神，请问在win10 19041.264, python 3.7.5 64bit环境下执行下面的代码：
browser_window = uiautomation.WindowControl(searchDepth=1, ClassName='MozillaWindowClass')
left, top, right, bottom = browser_window.BoundingRectangle
报出如下提示：
`Can not load UIAutomationCore.dll.
You may need to install Windows Update KB971513.
https://github.com/yinkaisheng/WindowsUpdateKB971513ForIUIAutomation
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "D:\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "smart_monkey.py", line 91, in start_test
    self.random_right_click()
  File "smart_monkey.py", line 51, in random_right_click
    x, y = self.random_move()
  File "smart_monkey.py", line 28, in random_move
    left, top, right, bottom = browser_window.BoundingRectangle
  File "D:\Python\Python37\lib\site-packages\uiautomation\uiautomation.py", line 5351, in BoundingRectangle
    rect = self.Element.CurrentBoundingRectangle
  File "D:\Python\Python37\lib\site-packages\uiautomation\uiautomation.py", line 5665, in Element
    self.Refind(maxSearchSeconds=TIME_OUT_SECOND, searchIntervalSeconds=self.searchInterval)
  File "D:\Python\Python37\lib\site-packages\uiautomation\uiautomation.py", line 5910, in Refind
    if not self.Exists(maxSearchSeconds, searchIntervalSeconds, False if raiseException else DEBUG_EXIST_DISAPPEAR):
  File "D:\Python\Python37\lib\site-packages\uiautomation\uiautomation.py", line 5860, in Exists
    control = FindControl(self.searchFromControl, self._CompareFunction, self.searchDepth, False, self.foundIndex)
  File "D:\Python\Python37\lib\site-packages\uiautomation\uiautomation.py", line 7683, in FindControl
    control = GetRootControl()
  File "D:\Python\Python37\lib\site-packages\uiautomation\uiautomation.py", line 7465, in GetRootControl
    return Control.CreateControlFromElement(_AutomationClient.instance().IUIAutomation.GetRootElement())
  File "D:\Python\Python37\lib\site-packages\uiautomation\uiautomation.py", line 51, in instance
    cls._instance = cls()
  File "D:\Python\Python37\lib\site-packages\uiautomation\uiautomation.py", line 62, in __init__
    raise ex
  File "D:\Python\Python37\lib\site-packages\uiautomation\uiautomation.py", line 57, in __init__
    self.IUIAutomation = comtypes.client.CreateObject("{ff48dba4-60ef-4201-aa87-54103eef594e}", interface=self.UIAutomationCore.IUIAutomation)
  File "D:\Python\Python37\lib\site-packages\comtypes\client\__init__.py", line 238, in CreateObject
    obj = comtypes.CoCreateInstance(clsid, clsctx=clsctx, interface=interface)
  File "D:\Python\Python37\lib\site-packages\comtypes\__init__.py", line 1225, in CoCreateInstance
    _ole32.CoCreateInstance(byref(clsid), punkouter, clsctx, byref(iid), byref(p))
  File "_ctypes/callproc.c", line 935, in GetResult
OSError: [WinError -2147221008] 尚未调用 CoInitialize。`
看提示信息要装windows的补丁包，但是您链接中放的都不是能够适用于win10系统的补丁，这样的问题该如何解决呢？请不吝指点指点。

**Comment by yinkaisheng** [comment]
rect = browser_window.BoundingRectangle
print(rect.left, rect.top, rect.right, rect.bottom)

参考demos
