### ISSUE TITLE
uiautomation中的comtypes库报错，如何解决？

### ISSUE THREAD

**Issue by lingduxingxi** [yinkaisheng/Python-UIAutomation-for-Windows#279]
![微信图片_20240425161803](https://github.com/yinkaisheng/Python-UIAutomation-for-Windows/assets/84306506/642c9dfd-daa6-48c8-bd97-02d1261329e3)
![微信图片_20240425161828](https://github.com/yinkaisheng/Python-UIAutomation-for-Windows/assets/84306506/1297a9cf-c3c0-47ea-bf4a-25decbccc903)

D:\uiautomation\python_bot>PYTHON D:\uiautomation\python_bot\daohang_bot.py
Traceback (most recent call last):
  File "D:\uiautomation\python_bot\daohang_bot.py", line 14, in <module>
    import uiautomation
  File "D:\Python34\lib\site-packages\uiautomation\__init__.py", line 4, in <mod
ule>
    from .uiautomation import *
  File "D:\Python34\lib\site-packages\uiautomation\uiautomation.py", line 23, in
 <module>
    import comtypes #need pip install comtypes
  File "D:\Python34\lib\site-packages\comtypes\__init__.py", line 263
    _case_insensitive_: bool
                      ^
SyntaxError: invalid syntax

D:\uiautomation\python_bot>PYTHON D:\uiautomation\python_bot\daohang_bot.py
Traceback (most recent call last):
  File "D:\uiautomation\python_bot\daohang_bot.py", line 14, in <module>
    import uiautomation
  File "D:\Python34\lib\site-packages\uiautomation\__init__.py", line 4, in <mod
ule>
    from .uiautomation import *
  File "D:\Python34\lib\site-packages\uiautomation\uiautomation.py", line 23, in
 <module>
    import comtypes #need pip install comtypes
  File "D:\Python34\lib\site-packages\comtypes\__init__.py", line 263
    _case_insensitive_: bool
                      ^
SyntaxError: invalid syntax

D:\uiautomation\python_bot>pip list

这个报错，怎么办？XP 32位系统

**Comment by yinkaisheng** [comment]
pip install comtypes==1.2.1
并且使用最新的uiautomation 2.0.19版本
