### ISSUE TITLE
Library Errors out before timeout to find a control not yet present with KeyError: 0

### ISSUE THREAD

**Issue by akshaykochar** [yinkaisheng/Python-UIAutomation-for-Windows#31]
Traceback (most recent call last):
  File "__init__.py", line 120, in wait_for_control
    if control.Exists(search_wait_time, uiautomation.SEARCH_INTERVAL):
  File "C:\Python27\Lib\site-packages\uiautomation\uiautomation.py", line 2424, in Exists
    control = FindControl(self.searchFromControl, self._CompareFunction, self.searchDepth, False, self.foundIndex)
  File "C:\Python27\Lib\site-packages\uiautomation\uiautomation.py", line 4299, in FindControl
    for child, depth in WalkControl(control, findFromSelf, maxDepth):
  File "C:\Python27\Lib\site-packages\uiautomation\uiautomation.py", line 4185, in WalkControl
    child = lastControl.GetFirstChildControl()
  File "C:\Python27\Lib\site-packages\uiautomation\uiautomation.py", line 2670, in GetFirstChildControl
    return Control.CreateControlFromElement(comEle)
  File "C:\Python27\Lib\site-packages\uiautomation\uiautomation.py", line 2790, in CreateControlFromElement
    return ControlDict[controlType](element)

**Comment by akshaykochar** [comment]
The control has not yet been generated. The library should wait until timeout expires to search for control right?

**Comment by yinkaisheng** [comment]
Please update the code and try again.

**Comment by akshaykochar** [comment]
Ok I will try it tomorrow and let you know. Thanks.

**Comment by akshaykochar** [comment]
@yinkaisheng  What do you mean by update the code?

**Comment by akshaykochar** [comment]
Do you have a release?

**Comment by yinkaisheng** [comment]
Just the git code.
I'll upload the package to pypi today.
