### ISSUE TITLE
版本1.1.8 所写的代码无法在1.1.12上运行

### ISSUE THREAD

**Issue by xiachunle** [yinkaisheng/Python-UIAutomation-for-Windows#49]
![image](https://user-images.githubusercontent.com/11811777/51515796-0b75d780-1e50-11e9-9380-c4f2746890af.png)
Traceback (most recent call last):
  File "D:/hqzf_ui_test/cases/sample.py", line 52, in <module>
    menu_item.MoveCursorToMyCenter()
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\uiautomation\uiautomation.py", line 2676, in MoveCursorToMyCenter
    return self.MoveCursor(simulateMove = simulateMove)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\uiautomation\uiautomation.py", line 2657, in MoveCursor
    left, top, right, bottom = self.BoundingRectangle
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\uiautomation\uiautomation.py", line 2643, in BoundingRectangle
    _AutomationClient.instance().dll.GetElementBoundingRectangle(ctypes.c_size_t(self.Element), ctypes.byref(rect))
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\uiautomation\uiautomation.py", line 2561, in Element
    self.Refind(maxSearchSeconds = TIME_OUT_SECOND, searchIntervalSeconds = self.searchWaitTime)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\uiautomation\uiautomation.py", line 2546, in Refind
    if not self.Exists(maxSearchSeconds, searchIntervalSeconds):
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\uiautomation\uiautomation.py", line 2515, in Exists
    if prev and not prev._element and not prev.Exists(maxSearchSeconds, searchIntervalSeconds):
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\uiautomation\uiautomation.py", line 2518, in Exists
    control = FindControl(self.searchFromControl, self._CompareFunction, self.searchDepth, False, self.foundIndex)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\uiautomation\uiautomation.py", line 4407, in FindControl
    if compareFunc(child, depth):
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\uiautomation\uiautomation.py", line 2488, in _CompareFunction
    raise KeyError('unsupported argument: {} in {} constructor'.format(key, self.__class__.__name__))
KeyError: 'unsupported argument: LocalizedControlType in MenuControl constructor'

**Comment by yinkaisheng** [comment]
Control构造函数里面，是没有LocalizedControlType的，如果你要用的话
先设置下
uiautomation.CHECK_SEARCH_PROPERTY_NAME = False

**Comment by yinkaisheng** [comment]
最终决定删除这个异常。
