### ISSUE TITLE
尝试pywinauto和 uiautomation共同使用，一旦导入pywinauto，在使用SetActive

### ISSUE THREAD

**Issue by qdwangjianjun** [yinkaisheng/Python-UIAutomation-for-Windows#81]
Traceback (most recent call last):
  File "D:/python_work/CAS_AutoTest/ut/ut.py", line 41, in <module>
    auto.WindowControl(searchDepth=1, AutomationId="myMainWindow", RegexName="Login").SetActive()
  File "D:\Python37-32\lib\site-packages\uiautomation\uiautomation.py", line 6907, in SetActive
    elif not IsWindowVisible(handle):
  File "D:\Python37-32\lib\site-packages\uiautomation\uiautomation.py", line 2124, in IsWindowVisible
    return bool(ctypes.windll.user32.IsWindowVisible(ctypes.c_void_p(handle)))
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

**Comment by yinkaisheng** [comment]
和 #65  是一个问题，里面有原因分析。
uiautomation里没有问题，你需要让其他模块作者改下。

**Comment by qdwangjianjun** [comment]
> 和 #65 是一类问题，里面有原因分析。
> uiautomation里没有问题，你需要让其他模块作者改下。

谢谢
