### ISSUE TITLE
uiautomation.WindowControl 查找失败

### ISSUE THREAD

**Issue by qdwangjianjun** [yinkaisheng/Python-UIAutomation-for-Windows#82]
代码
window = auto.WindowControl(AutomationId="myMainWindow",Name="PatientManager")
window.SetActive()

在将应用程序最小化后，运行如上代码，有的时候可以成功激活窗口，将窗口前置。有的时候提示失败：LookupError，无法找到窗口。

Traceback (most recent call last):
  File "D:/python_work/CAS_AutoTest/ut/ut.py", line 121, in <module>
    window.SetActive()
  File "D:\Python37-32\lib\site-packages\uiautomation\uiautomation.py", line 6903, in SetActive
    if self.IsTopLevel():
  File "D:\Python37-32\lib\site-packages\uiautomation\uiautomation.py", line 6181, in IsTopLevel
    handle = self.NativeWindowHandle
  File "D:\Python37-32\lib\site-packages\uiautomation\uiautomation.py", line 5539, in NativeWindowHandle
    handle = self.Element.CurrentNativeWindowHandle
  File "D:\Python37-32\lib\site-packages\uiautomation\uiautomation.py", line 5660, in Element
    self.Refind(maxSearchSeconds=TIME_OUT_SECOND, searchIntervalSeconds=self.searchInterval)
  File "D:\Python37-32\lib\site-packages\uiautomation\uiautomation.py", line 5908, in Refind
    raise LookupError('Find Control Timeout: ' + self.GetSearchPropertiesStr())
LookupError: Find Control Timeout: {AutomationId: 'myMainWindow', Name: 'PatientManager', ControlType: WindowControl}

**Comment by yinkaisheng** [comment]
参数里加上searchDepth提高查找速度，阅读中文readme，里面有简单介绍如何提高查找效率。

**Comment by qdwangjianjun** [comment]
> 参数里加上searchDepth提高查找速度，阅读中文readme，里面有简单介绍如何提高查找效率。

问题可能说的不够明白，即使加上searchDepth =1 。第一次能够成功运行，我将应用程序最小化，再次运行程序，程序就会运行失败。

**Comment by yinkaisheng** [comment]
最小化后程序在任务栏里还是在托盘？ 最小化后用automation.py或inspect能不能遍历到最小化的窗户，如果不能遍历到，确实无法查找。如果能遍历到，看看最小化后的窗口属性有什么不同。

有的程序最小化后在托盘里，窗口是隐藏的，无法获取。

**Comment by qdwangjianjun** [comment]
使用inspect 是可以看到窗口的，窗口是在任务栏
![image](https://user-images.githubusercontent.com/40756962/60858428-da903000-a240-11e9-92f2-bf3ef7da573e.png)

**Comment by yinkaisheng** [comment]
你圈的窗口Name是 Program Manager 和代码里Name不一样，确定是这个吗？

**Comment by qdwangjianjun** [comment]
额。。。圈错了，是倒数第三方个PatientManager

**Comment by yinkaisheng** [comment]
从这些信息，我看不出什么原因。

**Comment by qdwangjianjun** [comment]
![image](https://user-images.githubusercontent.com/40756962/61032816-c2611200-a3f4-11e9-934f-32d97330cba8.png)
![image](https://user-images.githubusercontent.com/40756962/61032851-d99fff80-a3f4-11e9-8678-bbb3a8acade4.png)

被测应用程序还有一个控制台log输出窗口，当这个窗口没有被最小化的情况下，我对主窗口进行查找就会失败。如果我手动将log窗口最小化，程序就运行没有问题。

**Comment by yinkaisheng** [comment]
在调用失败的时候，在你代码里加上
```
window = auto.WindowControl(searchDepth=1, AutomationId="myMainWindow", Name="PatientManager")
try:
    window.SetActive()
except LookupError as ex:
    auto.EnumAndLogControl(auto.GetRootControl(), maxDepth=1)
```
看看打印出的控件里有没有你要找的窗口
