### ISSUE TITLE
最新的2.0.3版本在WIN7的情况下无法运行，提示Can not load UIAutomationCore.dll.

### ISSUE THREAD

**Issue by stgfeng** [yinkaisheng/Python-UIAutomation-for-Windows#97]
Can not load UIAutomationCore.dll.
You may need to install Windows Update KB971513.
https://github.com/yinkaisheng/WindowsUpdateKB971513ForIUIAutomation
Exception in thread Thread-1:
Traceback (most recent call last):
  File "F:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "F:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "CircleAndRecord.pyw", line 288, in run_main
    if not motionWindow.Exists():
  File "F:\Anaconda3\lib\site-packages\uiautomation\uiautomation.py", line 5855,
 in Exists
    control = FindControl(self.searchFromControl, self._CompareFunction, self.se
archDepth, False, self.foundIndex)
  File "F:\Anaconda3\lib\site-packages\uiautomation\uiautomation.py", line 7678,
 in FindControl
    control = GetRootControl()
  File "F:\Anaconda3\lib\site-packages\uiautomation\uiautomation.py", line 7460,
 in GetRootControl
    return Control.CreateControlFromElement(_AutomationClient.instance().IUIAuto
mation.GetRootElement())
  File "F:\Anaconda3\lib\site-packages\uiautomation\uiautomation.py", line 51, i
n instance
    cls._instance = cls()
  File "F:\Anaconda3\lib\site-packages\uiautomation\uiautomation.py", line 62, i
n __init__
    raise ex
  File "F:\Anaconda3\lib\site-packages\uiautomation\uiautomation.py", line 57, i
n __init__
    self.IUIAutomation = comtypes.client.CreateObject("{ff48dba4-60ef-4201-aa87-
54103eef594e}", interface=self.UIAutomationCore.IUIAutomation)
  File "F:\Anaconda3\lib\site-packages\comtypes\client\__init__.py", line 238, i
n CreateObject
    obj = comtypes.CoCreateInstance(clsid, clsctx=clsctx, interface=interface)
  File "F:\Anaconda3\lib\site-packages\comtypes\__init__.py", line 1225, in CoCr
eateInstance
    _ole32.CoCreateInstance(byref(clsid), punkouter, clsctx, byref(iid), byref(p
))
  File "_ctypes/callproc.c", line 918, in GetResult
OSError: [WinError -2147221008] 尚未调用 CoInitialize。

**Comment by yinkaisheng** [comment]
参考demos\uiautomation_in_thread.py

**Comment by parfumix** [comment]
Hi, can you please help, I met the same issue? Maybe you have a chunk of code?

Thanks!
